FROM node:8.10

# Create app directory
RUN mkdir -p /src/frontend
WORKDIR /src/frontend

# Install app dependencies
COPY frontend/package.json /src/frontend/
RUN yarn 

# Bundle app source
COPY ./frontend /src/frontend

# Build and optimize react app
RUN yarn run build

EXPOSE 8000

# defined in package.json
CMD [ "yarn", "run", "start" ]
