#!/bin/bash

set -e

__frontend() {
    (
        cd frontend
        yarn
        yarn start
    )
}


__backend() {
    (
        cd clj-backend/another-flashcard-app
        lein run
    )
}


validate_args() {
  # looks through current file and finds functions whose names start with '__'
  acceptable_args="$(declare -F | sed -n "s/declare -f __//p" | tr '\n' ' ')"

  if [[ -z $1 ]]; then # if no argument was provided
    echo "Must provide an argument"
    printf "Available commands:\n$(declare -F | sed -n "s/declare -f __/ - /p")"
    exit 1
  fi
  if [[ ! " $acceptable_args " =~ .*\ $1\ .* ]]; then # argument not in list of functions beginning with '__'
      echo "Invalid argument: $1"
      printf "Available commands:\n$(declare -F | sed -n "s/declare -f __/ - /p")"
      exit 1
  fi
}

CMD=${1:-}
shift || true
if validate_args ${CMD}; then
  __${CMD} $@
  exit 0
fi
