FROM java:8-alpine
MAINTAINER Your Name <you@example.com>

ADD target/another-flashcard-app-0.0.1-SNAPSHOT-standalone.jar /another-flashcard-app/app.jar

EXPOSE 8080

CMD ["java", "-jar", "/another-flashcard-app/app.jar"]
